[template]
  incoming-hooks = ["Storyblok"]

[template.environment]
  STORYBLOK_PREVIEW_TOKEN = "gquTXrFGQ4ReztEBRee8Ygtt"
  STORYBLOK_PERSONAL_TOKEN = "Vy9a3iG3xUNRTIkeQ7E8Ggtt"
  STORYBLOK_SPACE_ID = "308530"
  LOCALE = "en-US"
  CURRENCY = "USD"
  SITE_LANG = "en"

[build]
  command = "npm run build"
  publish = "dist"