[template]
  incoming-hooks = ["Storyblok"]

[template.environment]
  STORYBLOK_PREVIEW_TOKEN = "gquTXrFGQ4ReztEBRee8Ygtt"
  STORYBLOK_PERSONAL_TOKEN = "Vy9a3iG3xUNRTIkeQ7E8Ggtt-262722-eG4jG2AdwsfMyKjzu9Ud"
  STORYBLOK_SPACE_ID = "308530"
  LOCALE = "es-ES"
  CURRENCY = "EUR"
  SITE_LANG = "es"

[build]
  command = "npm run build"
  publish = "dist"